import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const S = () => p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')).state);
const d = JSON.parse(JSON.stringify(base)); const s = d.state; s.missionNews = undefined; s.levelUps = []; s.titleNews = [];
Object.assign(s.world, { at: 'cairo', hour: 9, x: 214.3, y: 413.7 }); s.world.party.troops = { watchman: 1, fellah: 1 }; s.world.party.food = 20; s.cash = 3000;
s.world.known = [...new Set([...s.world.known, 'suez'])];
s.inventory = s.inventory.map((i, k) => (k < 2 ? { ...i, stored: false } : i));
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); localStorage.setItem('tof-skip-chapters', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(900);
await p.locator('[data-testid=place-suez]').dispatchEvent('click'); await p.click('[data-testid=speed-4]').catch(() => {});
await p.waitForSelector('[data-testid=road-encounter]', { timeout: 40000 });
await p.waitForTimeout(500);
await p.screenshot({ path: '/home/claude/shots/amb-standoff.png' });
await p.click('[data-testid=amb-fight]');
await p.waitForTimeout(1300);
await p.screenshot({ path: '/home/claude/shots/amb-battle.png' });
await p.click('[data-testid=amb-charge]', { timeout: 1500 }).catch(() => {});
await p.waitForSelector('[data-testid=encounter-result]', { timeout: 20000 });
await p.screenshot({ path: '/home/claude/shots/amb-result.png' });
console.log('result', await p.textContent('[data-testid=encounter-result]'));
console.log('troops', JSON.stringify((await S()).world.party.troops), 'cash', (await S()).cash);
console.log('errors', errors);
await b.close();
