import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const S = () => p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')).state);
const d = JSON.parse(JSON.stringify(base)); const s = d.state; s.missionNews = undefined; s.levelUps = [{ skill: 'haggling', level: 3 }]; s.titleNews = []; s.tipsSeen = ['map', 'town', 'auction', 'levelup', 'rumours', 'rashid', 'stock', 'audience'];
Object.assign(s.world, { at: 'giza', hour: 9, x: 146.9, y: 443.7 }); s.visitIdx = 0; s.encounter = null; s.dayOver = false; s.arrivals = [9.3, 16, 17.5]; s.queue = s.queue.slice(0, 3); s.world.party.food = 20;
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); localStorage.setItem('tof-skip-chapters', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(2500);
const h0 = (await S()).world.hour;
await p.screenshot({ path: '/home/claude/shots/calm-district.png' });
console.log('hour still', h0, 'levelup shown', await p.locator('[data-testid=levelup]').count());
await p.click('[data-testid=district-world]'); await p.waitForTimeout(600);
await p.locator('[data-testid=place-cairo]').dispatchEvent('click'); await p.waitForTimeout(600);
await p.screenshot({ path: '/home/claude/shots/calm-travel.png' });
console.log(await p.evaluate(() => ['.campaign', '.campaign-layer', '.world', '.world-map', '.world-canvas', '.world-card'].map((q) => { const e = document.querySelector(q); if (!e) return q + ' none'; const r = e.getBoundingClientRect(); return `${q} ${Math.round(r.x)},${Math.round(r.y)} ${Math.round(r.width)}x${Math.round(r.height)} ${getComputedStyle(e).transform}`; }).join('\n')));
await p.waitForTimeout(3000);
const st = await S();
console.log('after travel', st.world.at, st.world.hour.toFixed(2));
await p.waitForTimeout(2000);
console.log('stationary hour', (await S()).world.hour.toFixed(2));
console.log('errors', errors);
await b.close();
