import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const S = () => p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')).state);
const d = JSON.parse(JSON.stringify(base)); const s = d.state; s.missionNews = undefined; s.levelUps = []; s.titleNews = []; s.tipsSeen = ['map', 'town', 'auction', 'levelup', 'rumours', 'rashid', 'stock', 'audience'];
Object.assign(s.world, { at: 'giza', hour: 9, x: 146.9, y: 443.7 }); s.visitIdx = 0; s.encounter = null; s.dayOver = false; s.arrivals = [9.3, 9.6, 17.5]; s.queue = s.queue.slice(0, 3); s.stallShut = false;
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); localStorage.setItem('tof-skip-chapters', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(600);
await p.click('[data-testid=stall-shut]'); await p.click('[data-testid=clock-4]');
await p.waitForTimeout(3500);
await p.screenshot({ path: '/home/claude/shots/shut.png' });
let st = await S();
console.log('hour', st.world.hour.toFixed(2), 'visitIdx', st.visitIdx, 'pill', await p.locator('[data-testid=serve-waiting]').count(), 'shut', st.stallShut, 'empty notes', st.journal.filter((j) => j.text.includes('found it empty') && j.day === st.day).length);
await p.click('[data-testid=stall-shut]');
console.log('reopened', (await S()).stallShut, 'errors', errors);
await b.close();
