import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const d = JSON.parse(JSON.stringify(base)); const s = d.state; s.missionNews = undefined; s.levelUps = []; s.titleNews = []; s.tipsSeen = ['map', 'town', 'auction', 'levelup', 'rumours', 'rashid', 'stock', 'audience'];
Object.assign(s.world, { at: 'giza', hour: 9, x: 146.9, y: 443.7 }); s.visitIdx = 0; s.encounter = null; s.dayOver = false; s.arrivals = [9.2, 16, 17.5]; s.queue = s.queue.slice(0, 3);
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForSelector('[data-testid=serve-waiting]', { timeout: 20000 });
await p.screenshot({ path: '/home/claude/shots/step-1.png' });
await p.click('[data-testid=serve-waiting]'); await p.waitForSelector('[data-testid=stall]');
await p.waitForTimeout(800); await p.screenshot({ path: '/home/claude/shots/step-2.png' });
const who = await p.textContent('[data-testid=buyer-plate] .name').catch(() => '?');
await p.click('[data-testid=step-away]'); await p.waitForTimeout(800);
console.log('after step away: campaign', await p.locator('[data-testid=campaign]').count(), 'pill', await p.locator('[data-testid=serve-waiting]').count());
await p.screenshot({ path: '/home/claude/shots/step-3.png' });
await p.click('[data-testid=serve-waiting]'); await p.waitForTimeout(800);
console.log('resumed', who, '→', await p.textContent('[data-testid=buyer-plate] .name').catch(() => '?'));
console.log('errors', errors);
await b.close();
