import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage({ viewport: { width: 390, height: 780 } });
const errors = []; p.on('pageerror', (e) => errors.push(e.message)); p.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
const reqs = []; p.on('requestfinished', (r) => { const u = r.url(); if (u.includes('/audio/')) reqs.push(u.split('/audio/')[1]); });
const d = JSON.parse(JSON.stringify(base)); Object.assign(d.state.world, { at: 'cairo', x: 214.3, y: 413.7 }); d.state.day = 15; d.state.missionNews = undefined; d.state.levelUps = []; d.state.tipsSeen = ['map','town','auction','levelup','rumours'];
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
const S = async (tag) => { await p.waitForTimeout(3500); console.log(tag.padEnd(14), JSON.stringify(await p.evaluate(() => { const a = window.__tofAudio; return { ...a.state, stack: a.envStack?.map((e) => e.env + '/' + (e.music ?? '')) }; }))); };
await p.evaluate(() => { window.__tofAudio.startAmbience(); window.__tofAudio.startMusic('stall'); });
await S('stall');
await p.click('[data-testid=nav-map]'); await p.waitForTimeout(500);
for (const t of ['tip-ok','guide-skip']) if (await p.locator(`[data-testid=${t}]`).count()) await p.click(`[data-testid=${t}]`);
await S('map');
if (await p.locator('[data-testid=enter]').count()) await p.click('[data-testid=enter]');
await S('cairo town');
await p.click('[data-testid=house-cairo-garden-city]'); await S('garden walk');
await p.click('[data-testid=vpoi-floor]'); await p.waitForTimeout(4500); await S('grand floor');
await p.click('[data-testid=auction-leave]'); await p.waitForTimeout(300);
await p.click('[data-testid=venue-leave], [data-testid=venue-exit]').catch(() => {});
await S('after leave');
await p.evaluate(() => window.__tofAudio.sfx('meow')); await p.evaluate(() => window.__tofAudio.sfx('coins'));
await p.waitForTimeout(1500);
console.log('audio files requested:', [...new Set(reqs)].join(' '));
console.log('errors', errors);
await b.close();
