import { chromium } from 'playwright';
import fs from 'node:fs';
const d = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
d.state.day = 14; d.state.missionNews = undefined; d.state.levelUps = [];
Object.assign(d.state.world, { at: 'damascus' });
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto('http://localhost:4173/');
await p.evaluate((s) => { localStorage.setItem('threads-of-fortune-save', s); localStorage.setItem('tof-intro-seen-v2', '1'); }, JSON.stringify(d));
await p.reload();
if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(600);
await p.locator('[data-testid=hud-calendar]').first().click();
await p.waitForTimeout(400);
await p.screenshot({ path: '/home/claude/shots/cal-1.png' });
await p.locator('.cal-day:has(em:text-is("9"))').first().click().catch(()=>{});
await p.locator('button[aria-label="Next month"]').click();
await p.locator('.cal-day:has(em:text-is("9"))').first().click();
await p.waitForTimeout(200);
await p.screenshot({ path: '/home/claude/shots/cal-2.png' });
console.log('errors', errors);
await b.close();
