import { chromium } from 'playwright';
import fs from 'node:fs';
const d = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
Object.assign(d.state.world, { at: 'alexandria', x: 86.4, y: 387.2 });
d.state.cash = 3000;
d.state.skills = { speech: 160, haggling: 90, appraisal: 40, craft: 12, riding: 30, survival: 55, scholarship: 20, catkeeping: 14 };
d.state.manner = { honesty: 34, firmness: 18, kindness: 26, charm: -8 };
d.state.attire = { owned: ['galabiya', 'stambouli'], worn: 'stambouli', clean: 72 };
d.state.missionNews = undefined; d.state.levelUps = [];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto('http://localhost:4173/');
await p.evaluate((s) => { localStorage.setItem('threads-of-fortune-save', s); localStorage.setItem('tof-intro-seen-v2', '1'), localStorage.setItem('tof-films-once', '1'); }, JSON.stringify(d));
await p.reload();
if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(600);
await p.click('[data-testid=hud-rep]'); await p.waitForTimeout(400);
await p.screenshot({ path: '/home/claude/shots/char-1.png' });
await p.screenshot({ path: 'public/art/film/character.jpg', type: 'jpeg', quality: 82 });
await p.locator('[data-testid=skill-speech]').click(); await p.waitForTimeout(200);
await p.locator('[data-testid=skill-speech]').scrollIntoViewIfNeeded();
await p.screenshot({ path: '/home/claude/shots/char-2.png' });
await p.screenshot({ path: 'public/art/film/skills.jpg', type: 'jpeg', quality: 82 });
await p.click('[data-testid=character-close]');
await p.click('[data-testid=nav-map]'); await p.waitForTimeout(700);
if (await p.locator('[data-testid=guide-skip]').count()) await p.click('[data-testid=guide-skip]');
await p.screenshot({ path: '/home/claude/shots/mission-map.png' });
if (await p.locator('[data-testid=enter]').count()) await p.click('[data-testid=enter]');
await p.waitForTimeout(400);
await p.screenshot({ path: '/home/claude/shots/alex-town.png' });
await p.click('[data-testid=tab-market]'); await p.waitForTimeout(300);
const buy = p.locator('.mkt-row[data-testid^=buy-] .btn.primary:not([disabled])').first(); console.log('rows', await p.locator('.mkt-row[data-testid^=buy-]').count());
await buy.click(); await p.waitForTimeout(500);
await p.click('[data-testid=leave-settlement]').catch(() => {});
await p.waitForTimeout(500);
await p.screenshot({ path: '/home/claude/shots/mission-done.png' });
const st = await p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')).state);
console.log('mission', JSON.stringify(st.missions), 'trust', st.supplier.trust, 'errors', errors);
await b.close();
