import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const d = JSON.parse(JSON.stringify(base)); const s = d.state;
Object.assign(s.world, { at: 'giza', hour: 8 }); s.day = 2; s.queue = ['yusuf', 'mariam', 'hassan']; s.arrivals = [9, 11.25, 14.5]; s.visitIdx = 0; s.encounter = null; s.dayOver = false; s.onboard = {}; s.missionNews = undefined; s.levelUps = []; s.titleNews = []; s.reputation = 12;
s.errands = [{ id: '2-paper', kind: 'paper', label: "Read today's Giza Courier", hint: 'Tap 📰', reward: { xp: ['scholarship', 4] } }, { id: '2-radio', kind: 'radio', label: 'Listen to Radio Giza', hint: 'Tap 📻', reward: { xp: ['speech', 3] } }, { id: '2-sell', kind: 'sell', n: 2, label: 'Sell 2 rugs at the stall', hint: 'Wait at the stall.', reward: { cash: 60 } }];
await p.goto('http://localhost:4173/'); await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(700); for (const t of ['tip-ok', 'mission-ok']) if (await p.locator(`[data-testid=${t}]`).count()) await p.click(`[data-testid=${t}]`).catch(() => {});
await p.screenshot({ path: '/home/claude/shots/d2-1.png' });
await p.click('[data-testid=lesson-read]'); await p.waitForTimeout(500); await p.click('[data-testid=newspaper-close]'); await p.waitForTimeout(800);
await p.screenshot({ path: '/home/claude/shots/d2-2.png' });
await p.click('[data-testid=lesson-buyers-go]'); await p.waitForTimeout(600);
await p.screenshot({ path: '/home/claude/shots/d2-3.png' });
await p.locator('[data-testid=cust-shivakiar]').click(); await p.waitForTimeout(200);
await p.locator('[data-testid=cust-umm-kulthum]').scrollIntoViewIfNeeded(); await p.screenshot({ path: '/home/claude/shots/d2-4.png' });
await p.click('[data-testid=nav-stall]'); await p.waitForTimeout(400);
console.log('clock', await p.textContent('[data-testid=idle-clock]'), await p.textContent('[data-testid=idle-next]'));
await p.locator('[data-testid=lesson-radio] button:has-text("Later")').click(); await p.locator('[data-testid=lesson-map] button:has-text("Stay")').click();
await p.click('[data-testid=stall-wait]'); await p.waitForTimeout(1500);
console.log('after wait encounter?', await p.locator('[data-testid=stall-idle]').count() === 0, await p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')).state.world.hour));
console.log('errors', errors); await b.close();
