import { chromium } from 'playwright';
import fs from 'node:fs';
const d = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 760 }, deviceScaleFactor: 2 });
const errors = [];
p.on('pageerror', (e) => errors.push(e.message));
await p.goto('http://localhost:4173/');
await p.evaluate((s) => { localStorage.setItem('threads-of-fortune-save', s); localStorage.setItem('tof-intro-seen-v2', '1'); }, JSON.stringify(d));
await p.reload();
if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(500);
const st = await p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')));
console.log('migrated v', st.version, 'cash', st.state.cash, 'register', st.state.register, 'goals', st.state.goals.map((g) => g.label));
await p.screenshot({ path: '/home/claude/shots/econ-hud.png' });
await p.click('[data-testid=nav-ledger]');
await p.waitForTimeout(400);
await p.screenshot({ path: '/home/claude/shots/econ-ledger.png' });
await p.click('[data-testid=register-toggle]');
await p.waitForTimeout(300);
await p.locator('[data-testid=register]').scrollIntoViewIfNeeded();
await p.screenshot({ path: '/home/claude/shots/econ-register.png' });
await p.locator('[data-testid=reg-hereke]').scrollIntoViewIfNeeded();
await p.screenshot({ path: '/home/claude/shots/econ-register2.png' });
// Istanbul market with a high reputation
const s2 = await p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')));
Object.assign(s2.state.world, { at: 'istanbul', x: 200, y: 50 });
s2.state.reputation = 55; s2.state.cash = 250000;
await p.evaluate((s) => localStorage.setItem('threads-of-fortune-save', s), JSON.stringify(s2));
await p.reload();
if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(400);
await p.click('[data-testid=nav-map]');
await p.waitForTimeout(600);
if (await p.locator('[data-testid=enter]').count()) await p.click('[data-testid=enter]');
await p.waitForTimeout(400);
if (await p.locator('[data-testid=tab-market]').count()) await p.click('[data-testid=tab-market]');
await p.waitForTimeout(300);
const mk = p.locator('.mkt').first();
if (await mk.count()) await mk.scrollIntoViewIfNeeded();
await p.screenshot({ path: '/home/claude/shots/econ-istanbul.png' });
await p.click('[data-testid=nav-supplier]').catch(() => {});
await p.waitForTimeout(400);
await p.screenshot({ path: '/home/claude/shots/econ-rashid.png' });
console.log('errors', errors);
await b.close();
