import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const d = JSON.parse(JSON.stringify(base)); d.state.day = 46; d.state.missionNews = undefined; d.state.levelUps = []; d.state.titleNews = [];
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(600);
for (const t of ['tip-ok', 'mission-ok']) if (await p.locator(`[data-testid=${t}]`).count()) await p.click(`[data-testid=${t}]`).catch(() => {});
await p.screenshot({ path: '/home/claude/shots/hud-radio.png' });
await p.click('[data-testid=radio-btn]'); await p.waitForTimeout(400);
await p.click('[data-testid=radio-power]'); await p.waitForTimeout(9000);
await p.screenshot({ path: '/home/claude/shots/radio-en.png' });
console.log('en line', await p.textContent('.radio-captions p.on').catch(() => 'none'));
await p.click('[data-testid=radio-ar]'); await p.waitForTimeout(9000);
await p.screenshot({ path: '/home/claude/shots/radio-ar.png' });
console.log('ar line', await p.textContent('.radio-captions p.on').catch(() => 'none'));
await p.click('[data-testid=radio-close]');
console.log('errors', errors);
await b.close();
