import { chromium } from 'playwright';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 390, height: 780 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:5199'); await p.evaluate(() => localStorage.clear()); await p.reload();
await p.click('[data-testid=open-sandbox]');
await p.click('[data-testid=play-as-yourself]');
await p.fill('[data-testid=sbx-name]', 'Sami');
await p.setInputFiles('[data-testid=upload-head]', '/tmp/up-head.png');
await p.waitForSelector('[data-testid=sbx-preview]');
await p.screenshot({ path: '/tmp/w/sbx-modal.png' });
await p.click('[data-testid=sbx-start]');
await p.waitForTimeout(800);
console.log('look', await p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')||'{}').state?.heroLook?.kind), 'errs', errs);
await p.screenshot({ path: '/tmp/w/sbx-game.png' });
await b.close();
