import { chromium } from 'playwright';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 390, height: 780 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:5199'); await p.evaluate(() => localStorage.clear()); await p.reload();
await p.click('[data-testid=open-sandbox]');
await p.click('[data-testid=play-as-yourself]');
await p.click('[data-testid=sbx-next]'); await p.click('[data-testid=sbx-next]');
await p.fill('[data-testid=sbx-name]', 'Sami');
for (const k of ['full','stall','portrait']) await p.setInputFiles(`[data-testid=upload-${k}]`, `/tmp/up-${k}.png`);
await p.waitForSelector('[data-testid=sbx-next]:not([disabled])');
await p.click('[data-testid=sbx-next]');
await p.screenshot({ path: '/tmp/w/sbx-preview.png' });
await p.click('[data-testid=sbx-start]'); await p.waitForTimeout(800); await p.getByText('Begin Day One').click().catch(()=>{});
await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/w/sbx-game.png' });
const look = await p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')||'{}').state?.heroLook?.kind);
const size = await p.evaluate(() => (localStorage.getItem('threads-of-fortune-save')||'').length);
console.log('look', look, 'saveBytes', size, 'errs', errs);
await b.close();
