import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const S = () => p.evaluate(() => JSON.parse(localStorage.getItem('threads-of-fortune-save')).state);
const d = JSON.parse(JSON.stringify(base)); const s = d.state; s.missionNews = undefined; s.levelUps = []; s.titleNews = []; s.tipsSeen = ['map', 'town', 'auction', 'levelup', 'rumours', 'rashid', 'stock', 'audience'];
Object.assign(s.world, { at: 'giza', hour: 8, x: 146.9, y: 443.7 }); s.visitIdx = 0; s.encounter = null; s.dayOver = false; s.arrivals = [19.5, 19.6, 19.7]; s.queue = s.queue.slice(0, 3);
s.world.party.food = 20; s.inventory = s.inventory.map((i, k) => (k === 0 ? { ...i, stored: false } : i)); s.jobsDone = [];
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'), localStorage.setItem('tof-films-once', '1'); localStorage.setItem('tof-skip-chapters', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(800);
await p.click('[data-testid=district-world]'); await p.waitForTimeout(800);
await p.screenshot({ path: '/home/claude/shots/jobs-map.png' });
await p.click('[data-testid=jobs-btn]'); await p.waitForTimeout(400);
await p.screenshot({ path: '/home/claude/shots/jobs-list.png' });
const cash0 = (await S()).cash;
await p.click('[data-testid=job-go-saqqara-camp]'); await p.click('[data-testid=clock-4]');
for (let i = 0; i < 60 && (await S()).world.at !== 'saqqara'; i++) await p.waitForTimeout(300);
await p.waitForTimeout(500);
const st = await S();
console.log('at', st.world.at, 'jobsDone', st.jobsDone, 'cash', cash0, '→', st.cash);
await p.screenshot({ path: '/home/claude/shots/jobs-done.png' });
console.log('errors', errors);
await b.close();
