import { chromium } from 'playwright';
import fs from 'node:fs';
const base = JSON.parse(fs.readFileSync('/home/claude/shots/save.json', 'utf8'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
const dismiss = async () => { for (let i = 0; i < 4; i++) for (const t of ['tip-ok', 'mission-ok', 'guide-skip']) if (await p.locator(`[data-testid=${t}]`).count()) await p.click(`[data-testid=${t}]`).catch(() => {}); };
const d = JSON.parse(JSON.stringify(base)); const s = d.state; s.missionNews = undefined; s.levelUps = []; s.titleNews = []; s.tipsSeen = ['map', 'town', 'auction', 'levelup', 'rumours'];
Object.assign(s.world, { at: 'cairo', x: 214.3, y: 413.7, hour: 20 });
await p.goto('http://localhost:4173/');
await p.evaluate((x) => { localStorage.setItem('threads-of-fortune-save', x); localStorage.setItem('tof-intro-seen-v2', '1'), localStorage.setItem('tof-films-once', '1'); }, JSON.stringify(d));
await p.reload(); if (await p.locator('[data-testid=continue]').count()) await p.click('[data-testid=continue]');
await p.waitForTimeout(600); await dismiss();
await p.click('[data-testid=nav-map]'); await p.waitForTimeout(600); await dismiss();
if (await p.locator('[data-testid=leave-settlement]').count()) await p.click('[data-testid=leave-settlement]');
for (let i = 0; i < 4; i++) await p.click('button[aria-label="Zoom out"]').catch(() => {});
await p.locator('[data-testid=place-alexandria]').dispatchEvent('click'); await p.waitForTimeout(300);
await p.click('[data-testid=travel]');
const t0 = Date.now();
await p.waitForSelector('[data-testid=dawn]', { timeout: 60000 });
console.log('dawn after', (Date.now() - t0) / 1000, 's');
await p.screenshot({ path: '/home/claude/shots/v33-dawn.png' });
await p.click('[data-testid=dawn-paper]'); await p.waitForTimeout(700); await p.screenshot({ path: '/home/claude/shots/v33-dawn-paper.png' });
console.log('paper open', await p.locator('[data-testid=newspaper-close]').count());
await p.click('[data-testid=newspaper-close]'); await p.click('[data-testid=dawn-go]'); await p.waitForTimeout(1500);
console.log('dawn gone', await p.locator('[data-testid=dawn]').count(), 'errors', errors);
await b.close();
