"""First-visit films (Malek's grill, Arran's laboratory): record the documentary narration offline
with Kokoro (a stock synthetic British voice, bm_lewis: not a clone of anyone, and not the voice the
game uses for Arran himself), and write the caption timings.

  python3 tools/generate-intro-films.py --model /tmp/kokoro malek arran

Writes public/audio/intro/<who>.mp3 and src/data/introFilms.ts (each film's lines: what is said, what
the caption shows, and when each starts, in seconds). The films are public/video/<who>-intro.mp4.
"""
import argparse, json, os, subprocess
import numpy as np
import soundfile as sf
import imageio_ffmpeg
from kokoro_onnx import Kokoro

ROOT = os.path.join(os.path.dirname(__file__), '..')
# The lore, as a narrator would tell it: (spoken, caption). Fiction: the people and places are invented.
FILMS = {
    'malek': [
        ('Giza, nineteen twenty-five. Behind the bazaar, a charcoal grill, run by one man.', 'Giza, 1925. Behind the bazaar, a charcoal grill, run by one man.'),
        ('His name is Malek. His son made him Boo Rayan. The lane calls him Al-Mallem: the boss.', None),
        ('He has no partners, no patience, and four tables.', None),
        ('He expects the worst of every customer, every sheep, and every day.', None),
        ('And yet the kofta is the best in the lane, and the regulars always come back.', None),
        ('Whatever lives in his storeroom, he has never said.', None),
    ],
    'arran': [
        ('Arran Embleton. A British textile chemist, who came to Giza with a microscope, a balance, and a great many opinions about wool.', None),
        ('In his laboratory he tells you what a rug is really made of: the fibre, the dye, and whether the colour runs.', None),
        ('His signed reports travel with the rug. A buyer who doubts your word will believe his.', None),
        ('Bring him the books he needs, and he can test more. Ask him about the road, and he will tell you what to carry.', None),
        ('Careful, curious, and never in a hurry. In the bazaar, that makes him rare.', None),
    ],
}
VOICE, SPEED, LANG = 'bm_lewis', 0.9, 'en-gb'
SR = 24000
LEAD, GAP = 0.8, 0.55


def trim(x, thr=0.004):
    idx = np.where(np.abs(x) > thr)[0]
    if not len(idx):
        return x
    a = max(0, idx[0] - int(0.03 * SR)); b = min(len(x), idx[-1] + int(0.1 * SR))
    return x[a:b]


def record(k, who):
    parts, cues, t = [np.zeros(int(LEAD * SR), dtype=np.float32)], [], LEAD
    for spoken, shown in FILMS[who]:
        audio, sr = k.create(spoken, voice=VOICE, speed=SPEED, lang=LANG)
        assert sr == SR, sr
        audio = trim(audio.astype(np.float32))
        cues.append({'start': round(t, 2), 'end': round(t + len(audio) / SR, 2), 'text': shown or spoken})
        parts += [audio, np.zeros(int(GAP * SR), dtype=np.float32)]
        t += len(audio) / SR + GAP
    wav = f'/tmp/{who}-intro.wav'
    sf.write(wav, np.concatenate(parts), SR)
    out = os.path.join(ROOT, 'public', 'audio', 'intro', f'{who}.mp3')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), '-y', '-loglevel', 'error', '-i', wav, '-ac', '1', '-ar', '24000', '-codec:a', 'libmp3lame', '-b:a', '64k', out], check=True)
    print(f'{who}: {len(cues)} lines, {round(t, 1)} s, {os.path.getsize(out) // 1024} KB')
    return {'length': round(t, 2), 'cues': cues}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--model', default='/tmp/kokoro')
    ap.add_argument('who', nargs='+', choices=list(FILMS))
    a = ap.parse_args()
    k = Kokoro(os.path.join(a.model, 'kokoro-v1.0.onnx'), os.path.join(a.model, 'voices-v1.0.bin'))
    ts = os.path.join(ROOT, 'src', 'data', 'introFilms.ts')
    films = {who: record(k, who) for who in a.who}
    with open(ts, 'w') as f:
        f.write('// Generated by tools/generate-intro-films.py: the narration of each first-visit film, the caption\n')
        f.write('// for each line, and when it starts (seconds into public/audio/intro/<who>.mp3). Stock synthetic voice.\n')
        f.write('export interface IntroCue { start: number; end: number; text: string }\n')
        f.write('export const INTRO_FILMS: Record<string, { length: number; cues: IntroCue[] }> = ')
        f.write(json.dumps(films, indent=2, ensure_ascii=False))
        f.write(';\n')


if __name__ == '__main__':
    main()
