// Generated by tools/how-films/compose.py: each "How it plays" film, its length, and the narrator's lines
// with when each is said (seconds into public/video/how/<id>.mp4). Stock synthetic voice.
export interface HowCue { start: number; end: number; text: string }
export interface HowFilm { id: string; title: string; length: number; cues: HowCue[] }
export const HOW_FILMS: Record<string, HowFilm> = {
 "stall": {
  "id": "stall",
  "title": "Selling at your stall",
  "length": 51.49,
  "cues": [
   {
    "start": 0.45,
    "end": 4.8,
    "text": "This is your stall, in the lanes of Giza. Tap Stall to open it for the day."
   },
   {
    "start": 7.15,
    "end": 13.62,
    "text": "Nobody comes until you are ready. When you are, press Wait for a customer, and the next buyer walks up to your table."
   },
   {
    "start": 15.97,
    "end": 22.93,
    "text": "A buyer arrives. Under the picture you can see three things: their interest in buying, their patience, and how far they trust you."
   },
   {
    "start": 25.28,
    "end": 31.09,
    "text": "Lay a rug on the table. Pick one that suits what they are looking for. They will tell you what they think of it."
   },
   {
    "start": 33.44,
    "end": 40.02,
    "text": "Then talk. Ask about their room, tell the rug’s story, praise the craft. Every choice moves their interest up, or down."
   },
   {
    "start": 42.37,
    "end": 50.49,
    "text": "Watch their face and the bars. When their interest is high, name your price and close the sale. Every good sale adds to your name in the bazaar."
   }
  ]
 },
 "district": {
  "id": "district",
  "title": "Walking Giza",
  "length": 26.42,
  "cues": [
   {
    "start": 0.45,
    "end": 4.05,
    "text": "Giza is your home. The whole district is a map you can walk."
   },
   {
    "start": 6.4,
    "end": 8.99,
    "text": "Tap anywhere in the lanes, and Hassan walks there."
   },
   {
    "start": 11.34,
    "end": 18.04,
    "text": "Every marked place is somewhere you can go in: your stall, Bilgin’s coffee house, Arran’s laboratory, and Malek’s grill."
   },
   {
    "start": 20.39,
    "end": 25.42,
    "text": "The clock moves while you walk and work, so plan your day. The stall shuts at eight in the evening."
   }
  ]
 },
 "rashid": {
  "id": "rashid",
  "title": "Buying stock",
  "length": 43.22,
  "cues": [
   {
    "start": 0.45,
    "end": 8.11,
    "text": "Your rugs come from Uncle Rashid, the wholesaler who supplied your father for thirty years. The objective bar takes you straight to him."
   },
   {
    "start": 10.46,
    "end": 16.03,
    "text": "He shows you what he has today, each rug with his asking price. Tap one to look at it closely."
   },
   {
    "start": 18.38,
    "end": 21.94,
    "text": "Check the pattern, the wear and the size before you spend a piastre."
   },
   {
    "start": 24.29,
    "end": 28.85,
    "text": "You can haggle. Rashid enjoys it, but he knows exactly what his rugs are worth."
   },
   {
    "start": 31.2,
    "end": 37.3,
    "text": "Then pay in cash, or take the rug on credit and settle with him later. Buy well below what Giza will pay."
   },
   {
    "start": 39.65,
    "end": 42.22,
    "text": "The rug goes into your stock, ready for the stall."
   }
  ]
 },
 "inspect": {
  "id": "inspect",
  "title": "Inspecting a rug",
  "length": 29.26,
  "cues": [
   {
    "start": 0.45,
    "end": 4.84,
    "text": "Your stock lists every rug you own: what you paid, and what it usually sells for."
   },
   {
    "start": 7.19,
    "end": 10.09,
    "text": "Open a rug to inspect it, the way a buyer would."
   },
   {
    "start": 12.44,
    "end": 14.84,
    "text": "Zoom right in to see the knots and the colours."
   },
   {
    "start": 17.19,
    "end": 21.57,
    "text": "Turn it round and look again. Then read its condition, its weave and its history."
   },
   {
    "start": 23.92,
    "end": 28.26,
    "text": "Buyers who know rugs will ask. Know what you are selling before you name a price."
   }
  ]
 },
 "travel": {
  "id": "travel",
  "title": "Travelling",
  "length": 37.0,
  "cues": [
   {
    "start": 0.45,
    "end": 2.99,
    "text": "When Giza is not enough, zoom out to the world."
   },
   {
    "start": 5.34,
    "end": 12.81,
    "text": "This is the region in nineteen twenty-five: Egypt, Palestine, Syria, Iraq and Anatolia, with every town you can trade in."
   },
   {
    "start": 15.16,
    "end": 19.24,
    "text": "Tap a town to set off. Your route is drawn, and the clock starts to run."
   },
   {
    "start": 21.59,
    "end": 29.74,
    "text": "Speed the journey up, or stop at any time. Roads are quick and the desert is slow. Ferries, trains and ships cost a fare, but they save days."
   },
   {
    "start": 31.19,
    "end": 36.0,
    "text": "Arrive, and the town is yours to trade in: its buyers, its jobs and its sale rooms."
   }
  ]
 },
 "caravan": {
  "id": "caravan",
  "title": "Your caravan",
  "length": 33.62,
  "cues": [
   {
    "start": 0.45,
    "end": 2.8,
    "text": "Before a long road, open your caravan."
   },
   {
    "start": 5.15,
    "end": 9.88,
    "text": "At the top: how many days of food you carry, your pace, your strength, and how much you can load."
   },
   {
    "start": 12.23,
    "end": 15.68,
    "text": "Everyone eats. Buy bread, dates and water for the days ahead."
   },
   {
    "start": 18.03,
    "end": 23.08,
    "text": "Animals carry your rugs. A donkey is cheap. A camel carries far more, and walks further."
   },
   {
    "start": 25.43,
    "end": 32.62,
    "text": "And hire men to guard the road. Raiders ride some routes, but they leave a strong caravan alone. Guards are paid every morning."
   }
  ]
 },
 "cafe": {
  "id": "cafe",
  "title": "Chess and tawla",
  "length": 36.52,
  "cues": [
   {
    "start": 0.45,
    "end": 3.67,
    "text": "Bilgin’s coffee house is just round the corner from your stall."
   },
   {
    "start": 6.02,
    "end": 10.17,
    "text": "Talk to him for the news, or sit down at his chess table, or the tawla board."
   },
   {
    "start": 12.52,
    "end": 16.23,
    "text": "Play for tea, or for a few piastres, and choose how hard he plays."
   },
   {
    "start": 18.58,
    "end": 20.54,
    "text": "Throw the dice to see who starts."
   },
   {
    "start": 22.89,
    "end": 28.96,
    "text": "Tap a glowing checker, then the point where it goes. Bilgin answers every move, and laughs at his own jokes."
   },
   {
    "start": 31.31,
    "end": 34.62,
    "text": "Bear all fifteen off before he does, and the stake is yours."
   }
  ]
 },
 "news": {
  "id": "news",
  "title": "Paper and radio",
  "length": 26.65,
  "cues": [
   {
    "start": 0.45,
    "end": 3.89,
    "text": "Every day in the game is a real day of nineteen twenty-five."
   },
   {
    "start": 6.24,
    "end": 14.14,
    "text": "The Giza Courier carries that day’s real news. Read it in the morning: it moves prices, brings buyers, and makes roads safer, or worse."
   },
   {
    "start": 16.49,
    "end": 18.34,
    "text": "Or turn on Radio Giza."
   },
   {
    "start": 20.69,
    "end": 25.65,
    "text": "The radio reads the day’s news aloud while you work. Tap any line to hear it from there."
   }
  ]
 }
};
